<a href="https://colab.research.google.com/github/shuvookd/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **What is Numpy?**

Ans: **NumPy** is a scientific computing library for python.

Support large number of data in the form of multi-dimensional array and matrix.


### **NumPy Information**
NumPy 2d Array(Metrix)

NumPy 1d Array(Vector)

***Extension:***

.tsv(Tab)

.csv(Comma)

### **NumPy Installation**

pip install numpy

In [192]:
import numpy as np

### NumPy Function

Type of variable: **type(arrayName)**

Convert variable to boolean: **bool(var_name)**

arange() : **np.araange(start, End, Range)**

Linespace() : **np.linspace(start,End, line Space)**

Changing array dimention: **array_Name.reshape(row,column)**

Multidimentionl array to 1D array: **array_name.ravel()** or **array_name.flatten()**

Make Transpose: **array_name.transpose()**
or **array_name.T**

To know Dimension of array: **arrayName.ndim**

Size of array: **arrayName.size**

Shape of array: **arrayName.shape**

Data Type of array: **arrayName.dtype**

Creating Ones Matrix: **np.ones((row,colunm), dtype = int/float/bool/str)**

Creating Zeros Matrix: **np.zeros((row,colunm), dtype = int/float/bool/str)**


### **Create 1D Array**

In [193]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [194]:
# To know The type of variable: type()
type(array_1d)

numpy.ndarray

In [195]:
# To know The dimension of array: arrayName.ndim
array_1d.ndim

1

### **Creating 2D Array**

In [196]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [197]:
# To know The size of array: arrayName.size
array_2d.size

8

In [198]:
# To know The shape of array: arrayName.shape
#(Row, Colunm)
array_2d.shape

(2, 4)

In [199]:
# To know The Data Type of array: arrayName.dtype
array_2d.dtype

dtype('int64')

### **Creating One's Matrix**

In [200]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [201]:
ones_matrix = np.ones((2,3), dtype = int)
print(ones_matrix)

[[1 1 1]
 [1 1 1]]


### **Creating Zero's Matrix**

In [202]:
Zeros_matrix = np.zeros((3,4), dtype = bool)
print(Zeros_matrix)

[[False False False False]
 [False False False False]
 [False False False False]]


In [203]:
Zeros_matrix = np.zeros((3,4), dtype = str)
print(Zeros_matrix)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [204]:
#Convert string to boolean
empty_string = ''
print(bool(empty_string))


False


### **Create Empty Matrix**

In [205]:
# Expty matrix always show random Values
empty_matrix = np.empty((3,3))
print(empty_matrix)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


### **arrange()**

np.araange(start, End, Range)

In [206]:
#arange() : np.araange(start, End)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [207]:
#arange() : np.araange(start, End, Range)
even = np.arange(2,13,2)
print(even)

[ 2  4  6  8 10 12]


### **linespace()**

In [208]:
#linespace() : np.linspace(start,End, line Space)
ar = np.linspace(1,10,3)
print(ar)

[ 1.   5.5 10. ]


### **reshape()**

In [209]:
#Changing array dimention: array_Name.reshape(row,column)
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [210]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### **Converting Multidimentionl array to 1D array: ravel()**

In [211]:
arr_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [212]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### **transpose()**

In [213]:
arr_2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [214]:
arr_2d.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])