<a href="https://colab.research.google.com/github/shuvookd/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **What is Numpy?**

Ans: **NumPy** is a scientific computing library for python.

Support large number of data in the form of multi-dimensional array and matrix.


### **NumPy Information**
NumPy 2d Array(Metrix)

NumPy 1d Array(Vector)

***Extension:***

.tsv(Tab)

.csv(Comma)

### **NumPy Installation**

pip install numpy

In [29]:
import numpy as np

### NumPy Function

Type of variable: **type(arrayName)**

Convert variable to boolean: **bool(var_name)**

Dimension of array: **arrayName.ndim**

Size of array: **arrayName.size**

Shape of array: **arrayName.shape**

Data Type of array: **arrayName.dtype**

Creating Ones Matrix: **np.ones((row,colunm), dtype = int/float/bool/str)**

Creating Zeros Matrix: **np.zeros((row,colunm), dtype = int/float/bool/str)**


### **Create 1D Array**

In [30]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [31]:
# To know The type of variable: type()
type(array_1d)

numpy.ndarray

In [32]:
# To know The dimension of array: arrayName.ndim
array_1d.ndim

1

### **Creating 2D Array**

In [33]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [34]:
# To know The size of array: arrayName.size
array_2d.size

8

In [35]:
# To know The shape of array: arrayName.shape
#(Row, Colunm)
array_2d.shape

(2, 4)

In [36]:
# To know The Data Type of array: arrayName.dtype
array_2d.dtype

dtype('int64')

### **Creating One's Matrix**

In [37]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [38]:
ones_matrix = np.ones((2,3), dtype = int)
print(ones_matrix)

[[1 1 1]
 [1 1 1]]


### **Creating Zero's Matrix**

In [39]:
Zeros_matrix = np.zeros((3,4), dtype = bool)
print(Zeros_matrix)

[[False False False False]
 [False False False False]
 [False False False False]]


In [40]:
Zeros_matrix = np.zeros((3,4), dtype = str)
print(Zeros_matrix)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [41]:
#Convert string to boolean
empty_string = ''
print(bool(empty_string))


False


### **Create Empty Matrix**

In [42]:
# Expty matrix always show random Values
empty_matrix = np.empty((3,3))
print(empty_matrix)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
