<a href="https://colab.research.google.com/github/shuvookd/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **What is Numpy?**

Ans: **NumPy** is a scientific computing library for python.

Support large number of data in the form of multi-dimensional array and matrix.


### **NumPy Information**
NumPy 2d Array(Metrix)

NumPy 1d Array(Vector)

***Extension:***

.tsv(Tab)

.csv(Comma)

### **NumPy Installation**

pip install numpy

In [57]:
import numpy as np

### **NumPy Function**

Type of variable: **type(arrayName)**

Convert variable to boolean: **bool(var_name)**

arange() : **np.araange(start, End, Range)**

Linespace() : **np.linspace(start,End, line Space)**

Changing array dimention: **array_Name.reshape(row,column)**

Multidimentionl array to 1D array: **array_name.ravel()** or **array_name.flatten()**

Make Transpose: **array_name.transpose()**
or **array_name.T**

To know Dimension of array: **arrayName.ndim**

Size of array: **arrayName.size**

Shape of array: **arrayName.shape**

Data Type of array: **arrayName.dtype**

Creating Ones Matrix: **np.ones((row,colunm), dtype = int/float/bool/str)**

Creating Zeros Matrix: **np.zeros((row,colunm), dtype = int/float/bool/str)**



### **Mathematic Operation Using NumPy**

Matrix Addition: **np.add(array1_name, arrar2_name)**

Matrix Subtraction: **np.subsruct(array1_name , arrar2_name)**

Matrix Devision: **np.devide(array1_name , arrar2_name)**

Matrix Multiplication: **array1_name.dot(arrar2_name)**


***Maximum***


Find Maximum value of array: **array_name.max()**

Find Maximum value index of array: **array_name.argmax()**

Find Maximum value  of a column: **array_name.max(axis = 0)**

Find Maximum value  of a row: **array_name.max(axis = 1)**

***Minimum***


Find Minimum value of array: **array_name.min()**

Find Minimum value index of array: **array_name.argmin()**

Find Minimum value  of a column: **array_name.min(axis = 0)**

Find Minimum value  of a row: **array_name.min(axis = 1)**

***Sum***

Find Sum of all element in array: **np.sum(array_name)**

Sum of a Column in a matrix:**np.sum(a1, axis = 0)**

Sum of a Row in a matrix: **np.sum(a1, axis = 1)**

***Others***

Find Matrix Average: **np.mean(array_name)**

Find Matrix Square Root: **np.sqrt(array_name)**

Find Matrix Standerd Deviation: **np.std(array_name)**

Find Exponential: **np.exp(array_name)**

Find Logarithm: **np.log(array_name)**

Find 10 base Logarithm: **np.log10(array_name)**

### **Create 1D Array**

In [58]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [59]:
# To know The type of variable: type()
type(array_1d)

numpy.ndarray

In [60]:
# To know The dimension of array: arrayName.ndim
array_1d.ndim

1

### **Creating 2D Array**

In [61]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [62]:
# To know The size of array: arrayName.size
array_2d.size

8

In [63]:
# To know The shape of array: arrayName.shape
#(Row, Colunm)
array_2d.shape

(2, 4)

In [64]:
# To know The Data Type of array: arrayName.dtype
array_2d.dtype

dtype('int64')

### **Creating One's Matrix**

In [65]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [66]:
ones_matrix = np.ones((2,3), dtype = int)
print(ones_matrix)

[[1 1 1]
 [1 1 1]]


### **Creating Zero's Matrix**

In [67]:
Zeros_matrix = np.zeros((3,4), dtype = bool)
print(Zeros_matrix)

[[False False False False]
 [False False False False]
 [False False False False]]


In [68]:
Zeros_matrix = np.zeros((3,4), dtype = str)
print(Zeros_matrix)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [69]:
#Convert string to boolean
empty_string = ''
print(bool(empty_string))


False


### **Create Empty Matrix**

In [70]:
# Expty matrix always show random Values
empty_matrix = np.empty((3,3))
print(empty_matrix)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


### **arrange()**

np.araange(start, End, Range)

In [71]:
#arange() : np.araange(start, End)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [72]:
#arange() : np.araange(start, End, Range)
even = np.arange(2,13,2)
print(even)

[ 2  4  6  8 10 12]


### **linespace()**

In [73]:
#linespace() : np.linspace(start,End, line Space)
ar = np.linspace(1,10,3)
print(ar)

[ 1.   5.5 10. ]


### **reshape()**

In [74]:
#Changing array dimention: array_Name.reshape(row,column)
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### **Converting Multidimentionl array to 1D array: ravel()**

In [76]:
arr_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### **transpose()**

In [78]:
arr_2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [79]:
arr_2d.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Mathematic Operation Using NumPy

In [80]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(1,10).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matrix Addition

In [81]:
a1 + a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [82]:
np.add(a1,a2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Matrix Subtraction

In [83]:
a1 - a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [84]:
np.subtract(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Matrix Devision

In [85]:
a1 / a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Matrix Multiplication

In [87]:
#Multiply with Index wise
a1 * a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [88]:
#Multiply with Index wise
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [89]:
#Multiply with element wise(1st Row, 2nd column...)
a1 @ a2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [90]:
a1.dot(a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### **Find Maximum**

In [91]:
#Maximum value in array
a1.max()

9

In [92]:
#Maximum value index in array
a1.argmax()

8

In [93]:
#Maximum value of a column
a1.max(axis = 0)

array([7, 8, 9])

In [94]:
#Maximum value of a row
a1.max(axis = 1)

array([3, 6, 9])

### **Find Minimum**

In [95]:
#Minimum value in array
a1.min()

1

In [96]:
##Minimum value index in array
a1.argmin()

0

In [97]:
#Minimum value of a column
a1.min(axis = 0)

array([1, 2, 3])

In [98]:
#Minimum value of a column
a1.min(axis = 1)

array([1, 4, 7])

### **Matrix All element Sum**

In [99]:
#Sum of all element in a matrix
np.sum(a1)

45

In [100]:
#Sum of a Column in a matrix
np.sum(a1, axis = 0)

array([12, 15, 18])

In [101]:
#Sum of a Row in a matrix
np.sum(a1, axis = 1)

array([ 6, 15, 24])

### **Marix Average**

In [102]:
np.mean(a1)

5.0

### **Matrix Square Root find**

In [103]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### **Find Standerd Devision**

In [104]:
np.std(a1)

2.581988897471611

### **Find Exponential**

In [105]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### **Find Log**

In [106]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [107]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])