<a href="https://colab.research.google.com/github/shuvookd/Machine_Learning/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **What is Numpy?**

Ans: **NumPy** is a scientific computing library for python.

Support large number of data in the form of multi-dimensional array and matrix.


### **NumPy Information**
NumPy 2d Array(Metrix)

NumPy 1d Array(Vector)

***Extension:***

.tsv(Tab)

.csv(Comma)

### **NumPy Installation**

pip install numpy

In [ ]:
import numpy as np

### **NumPy Function**

Type of variable: **type(arrayName)**

Convert variable to boolean: **bool(var_name)**

arange() : **np.araange(start, End, Range)**

Linespace() : **np.linspace(start,End, line Space)**

Changing array dimention: **array_Name.reshape(row,column)**

Multidimentionl array to 1D array: **array_name.ravel()** or **array_name.flatten()**

Make Transpose: **array_name.transpose()**
or **array_name.T**

To know Dimension of array: **arrayName.ndim**

Size of array: **arrayName.size**

Shape of array: **arrayName.shape**

Data Type of array: **arrayName.dtype**

Creating Ones Matrix: **np.ones((row,colunm), dtype = int/float/bool/str)**

Creating Zeros Matrix: **np.zeros((row,colunm), dtype = int/float/bool/str)**



### **Mathematic Operation Using NumPy**

Matrix Addition: **np.add(array1_name, arrar2_name)**

Matrix Subtraction: **np.subsruct(array1_name , arrar2_name)**

Matrix Devision: **np.devide(array1_name , arrar2_name)**

Matrix Multiplication: **array1_name.dot(arrar2_name)**


***Maximum***


Find Maximum value of array: **array_name.max()**

Find Maximum value index of array: **array_name.argmax()**

Find Maximum value  of a column: **array_name.max(axis = 0)**

Find Maximum value  of a row: **array_name.max(axis = 1)**

***Minimum***


Find Minimum value of array: **array_name.min()**

Find Minimum value index of array: **array_name.argmin()**

Find Minimum value  of a column: **array_name.min(axis = 0)**

Find Minimum value  of a row: **array_name.min(axis = 1)**

***Sum***

Find Sum of all element in array: **np.sum(array_name)**

Sum of a Column in a matrix:**np.sum(a1, axis = 0)**

Sum of a Row in a matrix: **np.sum(a1, axis = 1)**

***Others***

Find Matrix Average: **np.mean(array_name)**

Find Matrix Square Root: **np.sqrt(array_name)**

Find Matrix Standerd Deviation: **np.std(array_name)**

Find Exponential: **np.exp(array_name)**

Find Logarithm: **np.log(array_name)**

Find 10 base Logarithm: **np.log10(array_name)**

***Array Slicing: Go to Code for Details***

### **Create 1D Array**

In [ ]:
array_1d = np.array([1,2,3,4])
print(array_1d)

[1 2 3 4]


In [ ]:
# To know The type of variable: type()
type(array_1d)

numpy.ndarray

In [ ]:
# To know The dimension of array: arrayName.ndim
array_1d.ndim

1

### **Creating 2D Array**

In [ ]:
array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)


[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
# To know The size of array: arrayName.size
array_2d.size

8

In [ ]:
# To know The shape of array: arrayName.shape
#(Row, Colunm)
array_2d.shape

(2, 4)

In [ ]:
# To know The Data Type of array: arrayName.dtype
array_2d.dtype

dtype('int64')

### **Creating One's Matrix**

In [ ]:
matrix_1s = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(matrix_1s)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
ones_matrix = np.ones((2,3), dtype = int)
print(ones_matrix)

[[1 1 1]
 [1 1 1]]


### **Creating Zero's Matrix**

In [ ]:
Zeros_matrix = np.zeros((3,4), dtype = bool)
print(Zeros_matrix)

[[False False False False]
 [False False False False]
 [False False False False]]


In [ ]:
Zeros_matrix = np.zeros((3,4), dtype = str)
print(Zeros_matrix)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [ ]:
#Convert string to boolean
empty_string = ''
print(bool(empty_string))


False


### **Create Empty Matrix**

In [ ]:
# Expty matrix always show random Values
empty_matrix = np.empty((3,3))
print(empty_matrix)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]


### **arrange()**

np.araange(start, End, Range)

In [ ]:
#arange() : np.araange(start, End)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
#arange() : np.araange(start, End, Range)
even = np.arange(2,13,2)
print(even)

[ 2  4  6  8 10 12]


### **linespace()**

In [ ]:
#linespace() : np.linspace(start,End, line Space)
ar = np.linspace(1,10,3)
print(ar)

[ 1.   5.5 10. ]


### **reshape()**

In [ ]:
#Changing array dimention: array_Name.reshape(row,column)
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


### **Converting Multidimentionl array to 1D array: ravel()**

In [ ]:
arr_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

### **transpose()**

In [ ]:
arr_2d.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
arr_2d.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### Mathematic Operation Using NumPy

In [ ]:
a1 = np.arange(1,10).reshape(3,3)
a2 = np.arange(1,10).reshape(3,3)
print(a1)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Matrix Addition

In [ ]:
a1 + a2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
np.add(a1,a2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### Matrix Subtraction

In [ ]:
a1 - a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.subtract(a1,a2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Matrix Devision

In [ ]:
a1 / a2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.divide(a1,a2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Matrix Multiplication

In [ ]:
#Multiply with Index wise
a1 * a2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
#Multiply with Index wise
np.multiply(a1,a2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [ ]:
#Multiply with element wise(1st Row, 2nd column...)
a1 @ a2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [ ]:
a1.dot(a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

### **Find Maximum**

In [ ]:
#Maximum value in array
a1.max()

9

In [ ]:
#Maximum value index in array
a1.argmax()

8

In [ ]:
#Maximum value of a column
a1.max(axis = 0)

array([7, 8, 9])

In [ ]:
#Maximum value of a row
a1.max(axis = 1)

array([3, 6, 9])

### **Find Minimum**

In [ ]:
#Minimum value in array
a1.min()

1

In [ ]:
##Minimum value index in array
a1.argmin()

0

In [ ]:
#Minimum value of a column
a1.min(axis = 0)

array([1, 2, 3])

In [ ]:
#Minimum value of a column
a1.min(axis = 1)

array([1, 4, 7])

### **Matrix All Element Sum**

In [ ]:
#Sum of all element in a matrix
np.sum(a1)

45

In [ ]:
#Sum of a Column in a matrix
np.sum(a1, axis = 0)

array([12, 15, 18])

In [ ]:
#Sum of a Row in a matrix
np.sum(a1, axis = 1)

array([ 6, 15, 24])

### **Marix Average**

In [ ]:
np.mean(a1)

5.0

### **Matrix Square Root find**

In [ ]:
np.sqrt(a1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

### **Find Standerd Deviation**

In [ ]:
np.std(a1)

2.581988897471611

### **Find Exponential**

In [ ]:
np.exp(a1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

### **Find Log**

In [ ]:
np.log(a1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [ ]:
np.log10(a1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

### **Array Slicing**

In [ ]:
matrix  = np.arange(1,101).reshape(10,10)
print(matrix)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [ ]:
#Find value by index
matrix[0,0]

1

In [ ]:
matrix[0,0].ndim

0

In [ ]:
# Find Row
matrix[0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Find Column
matrix[:,0]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
# Find Column
matrix[:,0:1]

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51],
       [61],
       [71],
       [81],
       [91]])

In [ ]:
# checking
matrix[:,0:1].ndim

2

In [ ]:
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#Print 1,2,3rd row and 1,2,3rd column
matrix[1:4,1:4]

array([[12, 13, 14],
       [22, 23, 24],
       [32, 33, 34]])

In [ ]:
#Print all row and 2nd and 3rd column
matrix[:, 1:3]

array([[ 2,  3],
       [12, 13],
       [22, 23],
       [32, 33],
       [42, 43],
       [52, 53],
       [62, 63],
       [72, 73],
       [82, 83],
       [92, 93]])

In [ ]:
#Print full matrix
matrix[:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#Print full matrix
matrix[:,:]

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
#To know item store space
matrix.itemsize

8

In [ ]:
#To know DataType
matrix.dtype

dtype('int64')